// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectOwner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UsedBudget")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Budget = 100000m,
                            HourlyRate = 150m,
                            ProjectName = "Contoso B2B Implementation",
                            ProjectOwner = "Jack Johnson",
                            UsedBudget = 5000m
                        },
                        new
                        {
                            ProjectId = 2,
                            Budget = 75000m,
                            HourlyRate = 210m,
                            ProjectName = "Contoso DC migration",
                            ProjectOwner = "Michael Smith",
                            UsedBudget = 0m
                        },
                        new
                        {
                            ProjectId = 3,
                            Budget = 25000m,
                            HourlyRate = 150m,
                            ProjectName = "Fabrikam Landing Zone Design",
                            ProjectOwner = "Michael Smith",
                            UsedBudget = 300m
                        },
                        new
                        {
                            ProjectId = 4,
                            Budget = 275000m,
                            HourlyRate = 160m,
                            ProjectName = "Packt E-commerce Site Build",
                            ProjectOwner = "Lisa Brown",
                            UsedBudget = 22000m
                        },
                        new
                        {
                            ProjectId = 5,
                            Budget = 55000m,
                            HourlyRate = 160m,
                            ProjectName = "Sailing Vessels Auction App MVP",
                            ProjectOwner = "Lisa Brown",
                            UsedBudget = 46750m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
